### ISSUE TITLE
Is it possible to defeat all enemies instead of attacking boss as soon as it appears?

### ISSUE THREAD

**Issue by latot** [Egoistically/ALAuto#79] opened 2020-02-06 15:08 UTC
Hi, actually i have set RetreatAfter to 0, but is curios, i check the battle but is not clearing the map, just when the final ship appears go to the finish battle instead clear the entire map.

Maybe, "Clear the Map" in the wiki menas just finish the map instead clear it.

Thx.

**Comment by Egoistically** [comment] 2020-02-06 15:34
That's a known bug.

**Comment by latot** [comment] 2020-02-06 15:37
:O right, is the node collection bug? https://github.com/Egoistically/ALAuto/issues/38?

**Comment by Egoistically** [comment] 2020-02-06 15:52
Nop, different one.

**Comment by latot** [comment] 2020-02-06 15:54
D: well, if there is an already open issue for this, close this issue plis.

Thx.

**Comment by Egoistically** [comment] 2020-02-06 15:58
There's no open issue about it, so we'll use this one.
Bug: Sometimes, when boss spawns, the bot doesn't detect it and instead starts clearing the whole map. It is caused by the input swipes if no ships are found.

**Comment by latot** [comment] 2020-02-06 16:11
mm, I think here is a little confusion xD

Actual behavior is, when the boss appears we wo directly for it and the map finish, this is working pretty fine.

But i would like to clear the entire map instead go to the boss when appear.

Maybe if i set RetreatAfter: 99 would do this?

**Comment by Egoistically** [comment] 2020-02-06 16:29
Ah, that's not a feature neither do I have any intentions on adding it.

**Comment by hjk22** [comment] 2020-02-25 22:44
> Bug: Sometimes, when boss spawns, the bot doesn't detect it and instead starts clearing the whole map. It is caused by the input swipes if no ships are found.

I'll open a new issue for this.

> I would like to clear the entire map instead go to the boss when appear.

As @Egoistically said, that's not a feature and we're not planning on adding it anytime soon (if ever). Still, in the latest version we have added a new setting which disables the search for boss fleet until a certain number of enemies is defeated: you could try using a value sufficiently high to defeat all mobs and see if it works (even if it isn't its intended purpose).
Closing this issue now.

**Closed as completed by hjk22** 2020-02-25 22:44 UTC
Labels: documentation, question
