### ISSUE TITLE
Get's stuck when unable to reach enemy 

### ISSUE THREAD

**Issue by nooblvlboss** [Egoistically/ALAuto#33] opened 2019-12-10 14:36 UTC
When the bot selects an enemy that the fleet can't reach, it seems to be stuck there. This seems to only happen if the enemy is not a boss. I had to manually select an enemy.
<img width="554" alt="bot error log" src="https://user-images.githubusercontent.com/58737948/70538604-59e1b100-1b9d-11ea-99e6-71dca65b597a.PNG">

**Comment by Egoistically** [comment] 2019-12-10 18:04
Was this on an event map?

**Comment by JustShinobi** [comment] 2019-12-10 18:05
> Was this on an event map?

can we using on event map? LUL

**Comment by nooblvlboss** [comment] 2019-12-10 18:49
No it was on 8-4. I think the issue was I exited the map and came back manually (like when the bot killed 1 enemy). It went on clearing map as usual but then got stuck when it was unable to access. The bot seems fine if I don't touch it at all though.

**Comment by Egoistically** [comment] 2019-12-10 19:07
> can we using on event map? LUL

Yes and no, assets can be manually added but it will treat it as a normal map.

> 
> 
> No it was on 8-4. I think the issue was I exited the map and came back manually (like when the bot killed 1 enemy). It went on clearing map as usual but then got stuck when it was unable to access. The bot seems fine if I don't touch it at all though.

Yeah you are not supposed to interfere in any way. So now it works fine?

**Comment by nooblvlboss** [comment] 2019-12-10 19:17
Yep!

**Comment by JustShinobi** [comment] 2019-12-10 20:10
Farming on 10-3 and got stuck like our friend

![](https://i.imgur.com/m2CMpGc.png)

the bot keep click on mark

![](https://i.imgur.com/mLEzCVQ.png)

I dont do anything, was the 3rd run without problems.

**Comment by nooblvlboss** [comment] 2019-12-10 23:03
Sorry for re-opening this issue. Just woke up, and same thing had happened.

**Comment by hjk22** [comment] 2019-12-11 00:33
I believe the problem is that the target type is added together with the coordinates to the blacklist, so the script is unable to correctly filter them out. In `combat.py` [line 282](https://github.com/Egoistically/ALAuto/blob/b4ce103b5ded0842ee8db9cf6aabbdeb0bc55fea/modules/combat.py#L282) to the variable `location` is assigned the result of the `get_closest_target` function, which contains also the target type. Try substituting this line with `location = self.get_closest_target(self.blacklist)[0:2]`, this should solve this issue.

**Comment by JustShinobi** [comment] 2019-12-11 00:43
> I believe the problem is that the target type is added together with the coordinates to the blacklist, so the script is unable to correctly filter them out. In `combat.py` [line 282](https://github.com/Egoistically/ALAuto/blob/b4ce103b5ded0842ee8db9cf6aabbdeb0bc55fea/modules/combat.py#L282) to the variable `location` is assigned the result of the `get_closest_target` function, which contains also the target type. Try substituting this line with `location = self.get_closest_target(self.blacklist)[0:2]`, this should solve this issue.

Will try, thanks.

**Comment by Egoistically** [comment] 2019-12-11 00:53
Should be fixed with @hjk22's solution. Pushed it already https://github.com/Egoistically/ALAuto/commit/01e18b5a06064e3c8964802a30fe2d1d7112abd9.
Please let me know whether or not it works.

**Comment by JustShinobi** [comment] 2019-12-11 01:48
looks like it didn't work, farming at 7-3 got stuck here

![](https://i.imgur.com/0G3y1On.png)

I marked X where the bot was clicking

![](https://i.imgur.com/IzXPnaw.png)

**Comment by Egoistically** [comment] 2019-12-11 02:18
It's a different issue at least, the blacklist checks for exact coordinates and those are different by a pixel or a few. Some kind of checker for near coordinates needs to be coded to solve that.
Will check it out tomorrow.

**Comment by JustShinobi** [comment] 2019-12-11 03:27
> It's a different issue at least, the blacklist checks for exact coordinates and those are different by a pixel or a few. Some kind of checker for near coordinates needs to be coded to solve that.
> Will check it out tomorrow.

alright, no problem.

Just another example

![](https://i.imgur.com/blAXSk4.png)

I marked X where the bot was clicking

I noticed that whenever the node ends in this pattern gives error in this map.

7-3 btw.

![](https://i.imgur.com/B1J1Kn5.png)

**Comment by Egoistically** [comment] 2019-12-12 04:00
@whoamikyo Try this: https://github.com/Egoistically/ALAuto/commit/8551e862a2ca02a46d5502ec1d19a82ce90df826, now it filters close coordinates too.
I have no idea about the bot clicking on that red cross, it is kinda nonsense.

**Comment by JustShinobi** [comment] 2019-12-12 15:17
> @whoamikyo Try this: [8551e86](https://github.com/Egoistically/ALAuto/commit/8551e862a2ca02a46d5502ec1d19a82ce90df826), now it filters close coordinates too.
> I have no idea about the bot clicking on that red cross, it is kinda nonsense.

Testing now, thanks.

**Comment by JustShinobi** [comment] 2019-12-12 17:42
Looks like it didn't work, the bot tries to reach the target but even giving error because the path is closed, he keeps trying.

![](https://i.imgur.com/noUGrpH.png)

![](https://i.imgur.com/7pCGhl5.png)

**Comment by Egoistically** [comment] 2019-12-13 01:20
@whoamikyo Now? https://github.com/Egoistically/ALAuto/commit/5419ff24eaee965a73b1d00b24f30fa45d3ba169.

**Comment by JustShinobi** [comment] 2019-12-13 01:21
let me test again.

**Closed as completed** 2019-12-16 08:54 UTC
